framework: RUFMUA          # Name of cif file
unitcell: [4, 3, 3]        # Unit cell replication
temperature: 77            # System temperature (K)
pressure: 100              # System pressure (bar)
init_cycles: 2000          # Initialization MC cycles
cycles: 10000              # Production MC cycles
cutoff: 12                 # Cut-off radius (Angstrom)
forcefield: UFF            # Force field definition
charge: no                 # Use charges from cif file
print_every: 2000          # Print data every n steps
movies: no                 # Generate movies (snapshots)
movies_every: 10000        # Generate movies enery n steps
void_fraction: false       # Define void fraction for excess adsorption
components:
  - name: H2
    definition: TraPPE
    mol_fraction: false    # Use only for mixture adsorption
    p_translation: 0.5
    p_rotation: 0.0
    p_reinsertion: 0.5
    p_swap: 1.0
    create_molecules: 0
