theme: jekyll-theme-minimal
title: Chemistry tools tutorials/scripts
description: Tutorials and scripts for several computational chemistry tools
show_downloads: True
navigation:
  - title: KBS - Home
    url: https://kbsezginel.github.io
  - title: Chem. tools tutorials
    url: /
  - title: File conversion
    url: file-conversion
  - title: Visualization
    url: https://kbsezginel.github.io/visualization/
  - title: Avogadro
    url: avogadro
  - title: OpenBabel
    url: openbabel
  - title: RASPA
    url: raspa
  - title: LAMMPS
    url: lammps
  - title: EQeq
    url: eqeq
  - title: Packmol
    url: packmol
  - title: HostDesigner
    url: hostdesigner
